### ISSUE TITLE
Event store stream function goroutine

### ISSUE THREAD

**Issue by theredrad** [kubemq-io/kubemq-go#13]
The stream `send` function pushes the message into the `eventCh` and it's processed in another goroutine (https://github.com/kubemq-io/kubemq-go/blob/4b4e96da5642194ba6ebba0dd3acc70f92240788/events_store_client.go#L67), so while gracefully shutting down the application, it's possible to lose the message before pushing to the KubeMQ.

Is there any way (except time sleep) to wait for `send` goroutine before shutting down the application?

**Comment by kubemq** [comment]
Hi,
Not sure i understand the issue, how you are shutting it down ? cancel the context ?
Can you contact me on our Slack Channel and let's figure it out ?
Lior,

**Comment by theredrad** [comment]
With help of dear Lior, I could use this custom implementation of the event store client that waits for the response in the same goroutine:

https://github.com/kubemq-io/kubemq-sources/blob/a06c0f632c7c00eb71b3dd9e3dc8e8904555a433/targets/events-store/client.go
