### ISSUE TITLE
RPC error when sending to QueuesStreamClient

### ISSUE THREAD

**Issue by natnoc** [kubemq-io/kubemq-go#16]
Hi,

I occasionally get the following error:
```rpc error: code = Unknown desc = stan: connect request timeout (possibly wrong cluster ID?)```

Until now, I haven't quite found a pattern for this error to occur, but it is thrown after calling queuesClient.Send:
```
// this code is called in main.go, closing of client connection is deferred
queuesClient, err := kubemq.NewQueuesStreamClient(ctx,
		kubemq.WithAddress(host, grpcPort),
		kubemq.WithClientId(clientId),
		kubemq.WithTransportType(kubemq.TransportTypeGRPC))
	if err != nil {
		return nil, err
	}

...

// this code is called when a specific event occurs and errors occasionally.
res, err := queuesClient.Send(ctx, kubemq.NewQueueMessage().
		SetChannel(channel).SetMetadata(msg.Metadata).SetBody(msg.Body).SetTags(msg.Tags))
	if err != nil {
		logger.GetLogger(ctx).Error().Caller().Err(err).Send()
		return nil, err
	}

...
```

I have multiple services running in a minikube cluster in their own namespace and KubeMQ deployed with Helm according to the [docs](https://docs.kubemq.io/getting-started/create-cluster/helm). The services are deployed with Helm managed by Tilt for local development. All pods seem to be healthy, but I do see the exact same error message in either one of the kubemq-cluster pods. 

Any ideas on what causes this error?

**Comment by natnoc** [comment]
K8s version: 1.26.3

Go version: 1.20

KubeMQ Helm chart versions: 
![image](https://github.com/kubemq-io/kubemq-go/assets/18187489/011da57d-3bb6-45b0-b5d9-f43fb9b895ba)

**Comment by kubemq** [comment]
Not sure this is go sdk issue, please contact us on our slack channel.

**Comment by natnoc** [comment]
It appears that the error was caused by an invlid license key, just in case anyone else struggles with this. Thanks for the quick support!

**Comment by natnoc** [comment]
It appears that the error was caused by an invlid license key, just in case anyone else struggles with this. Thanks for the quick support!
