### ISSUE TITLE
go get -u github.com/kubemq-io/kubemq getting unknown revision error v1.5.1

### ISSUE THREAD

**Issue by myussufz** [kubemq-io/kubemq-go#4]
Hi, 
We are getting an error when downloading the kubemq-io/kubemq-go repo.

```console
$ go get -u github.com/kubemq-io/kubemq-go
go: finding github.com/kubemq-io/kubemq v1.5.1
go: github.com/kubemq-io/kubemq@v1.5.1: unknown revision v1.5.1
go: error loading module requirements
```

We realize this line in go.mod file causes the error.
```
github.com/kubemq-io/kubemq v1.5.1
```

**Comment by kubemq** [comment]
Hello,
Checking it and get back to you asap,
Are you using modules?

**Comment by myussufz** [comment]
Yeah, we are using modules.

**Comment by kubemq** [comment]
Hi,
I have updated the mod file,
Please try again.
Please be aware that KubeMQ-Go SDK requires a Go version capable of understanding /vN suffixed imports:
- 1.9.7+
- 1.10.3+
- 1.11+
- 1.12+

``` bash
# Go Modules
require github.com/kubemq-io/kubemq-go v1.2.5
```

**Comment by myussufz** [comment]
Yeah, now it is working, thank you.
