### ISSUE TITLE
invalid channel value, no wildcards are allowed

### ISSUE THREAD

**Issue by joyciep** [kubemq-io/kubemq-go#5]
Hi,

I'm getting this error when I try to subscribe to a channel wildcard (event store) `foo.*`

```
rpc error: code = Internal desc = Error 107: invalid channel value, no wildcards are allowed
```

Are wildcards not allowed in event store subscription?

**Comment by kubemq** [comment]
No, they are not allowed as all events are persisted. Events, commands and
queries supports wildcards but events store not. The same for queues.

**Comment by joyciep** [comment]
Okay, I'll just use events. Thanks!
