### ISSUE TITLE
Event.ClientId always empty on the receiver side

### ISSUE THREAD

**Issue by Aidamir** [kubemq-io/kubemq-go#9]
Hello. I was discovered the clientId option is always empty on the received event. However, the value is correctly set on the sender side. The following is the ouput of the    [real-time example, modified](https://github.com/Aidamir/kubemq-go/blob/master/examples/pubsub/real-time/main.go#L84) for isllustrating issue. 

~/prj/kubemq-go/examples/pubsub/real-time$ ./real-time
2020/05/29 09:31:58 
**Before sending ClientId:test-event-grpc-client**
2020/05/29 09:31:58 Receiver B - Event Received:
EventID: some-id
Channel: testing_event_channel
Metadata: some-metadata
Body: hello kubemq - sending single event
**ClientId:** 
2020/05/29 09:31:58 Receiver A - Event Received:
EventID: some-id
Channel: testing_event_channel
Metadata: some-metadata
Body: hello kubemq - sending single event
2020/05/29 09:31:58 Receiver B - Event Received:
EventID: some-event-id
Channel: testing_event_channel
Metadata: some-metadata
Body: hello kubemq - sending stream event
**ClientId:** 
2020/05/29 09:31:58 Receiver A - Event Received:
EventID: some-event-id
Channel: testing_event_channel
Metadata: some-metadata
Body: hello kubemq - sending stream event

It would be also greate to be able to get clientId from the *kubemq.Client. I have not found a way how to get it currently. 

Thanks.

**Comment by kubemq** [comment]
thank you for reporting the issue,
I have issued a fix
v.1.3.7

**Comment by Aidamir** [comment]
Thanks, You did fix for Real tiime Event, but the [similar](https://github.com/kubemq-io/kubemq-go/blob/master/grpc.go#L335) **issue still present on EventStore**

**Comment by kubemq** [comment]
I added a temp fix (v1.3.8) for this issue as the clientId value should be the value of the sender and not of the subscriber.
this issue is related to KubeMQ server.
the current temp solution is to set the subscriber clientId,
once it will be supported in KubeMQ side, we will set the sender clientId
I will keep this issue opened until it will be resolved in KubeMQ server.

**Comment by kubemq** [comment]
No change is planned to current behavior
